language: cpp

sudo: required
dist: focal

notifications: 
  email:
    recipients:
    - rncbc@rncbc.org
    on_success: change
    on_failure: always

branches:
  only:
  - master

before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt-5.15.2-focal
- sudo add-apt-repository --yes ppa:rncbc/libs-focal
- sudo apt-get update -qq

install:
- sudo apt-get install -qq qt515base qt515tools qt515translations 
- sudo apt-get install -qq qt515svg qt515wayland libgl-dev
- sudo apt-get install -qq libjack-dev libasound2-dev libsndfile1-dev
- sudo apt-get install -qq libvorbis-dev libmad0-dev libsamplerate-dev zlib1g-dev
- sudo apt-get install -qq ladspa-sdk dssi-dev liblo-dev librubberband-dev vst3sdk-dev
- sudo apt-get install -qq lv2-dev liblilv-dev libsratom-dev libsord-dev libserd-dev
- sudo apt-get install -qq libsuil-dev libaubio-dev libgtk2.0-dev

before_script:
- git fetch --unshallow --tags -q
- ./autogen.sh

script:
- source /opt/qt515/bin/qt515-env.sh
- cmake
- make
- sudo make install
